### ISSUE TITLE
Tornar opcional uso de ícones sociais e busca abaixo do menu

### ISSUE THREAD

**Issue by anapaulabrasa** [redelivre/kaingang#52]
É interessante que o administrador possa escolher utilizar ou não abaixo do menu as ferramentas de busca e redes sociais.

Há casos em que a organização não possui nenhuma conta em rede social, e aí a visualidade fica bem ruim, como no exemplo abaixo (em http://elaa.redelivre.org.br/)

![iconesredesocial](https://cloud.githubusercontent.com/assets/2422926/19489302/73aae5bc-9549-11e6-87a7-456a1726bd57.png)

**Comment by jacsonp** [comment]
pode parece meio bobo, mas seu eu tirar a busca, vai ficar sem busca mesmo?

**Comment by anapaulabrasa** [comment]
A intenção é que não fique "manco". Se eu desejo não utilizar os ícones das mídias sociais, devo também poder escolher não utilizar a busca neste local - já que há o widget de busca.
